<?php

namespace App\Http\Controllers;

use App\Models\Building;
use App\Models\KpiScorecard;
use App\Models\Location;
use App\Support\KpiScoring;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class KpiRecordController extends Controller
{
    public function index(Request $request)
    {
        $records = KpiScorecard::withCount('lines')
            ->withSum('lines', 'merit')
            ->when($request->location_id, fn ($q, $v) => $q->where('location_id', $v))
            ->when($request->building_id, fn ($q, $v) => $q->where('building_id', $v))
            ->when($request->month, fn ($q, $v) => $q->where('date', 'like', $v . '%'))
            ->latest('date')
            ->paginate(15)
            ->withQueryString();

        return view('kpi.records.index', [
            'records'    => $records,
            'locations'  => Location::orderBy('name')->get(),
            'buildings'  => Building::orderBy('name')->get(['id', 'name']),
            'filters'    => $request->only(['location_id', 'building_id', 'month']),
        ]);
    }

    public function show(KpiScorecard $record)
    {
        $record->load(['lines' => fn ($q) => $q->with('group')->orderBy('id')]);

        return view('kpi.records.show', compact('record'));
    }

    public function edit(KpiScorecard $record)
    {
        $record->load(['lines' => fn ($q) => $q->with('group')->orderBy('id')]);

        return view('kpi.records.edit', compact('record'));
    }

    public function update(Request $request, KpiScorecard $record)
    {
        $data = $request->validate([
            'comments'       => ['nullable', 'string'],
            'lines'          => ['array'],
            'lines.*.scored' => ['nullable', 'integer', 'min:0'],
        ]);

        DB::transaction(function () use ($record, $data) {
            $record->update(['comments' => $data['comments'] ?? null]);

            foreach ($data['lines'] ?? [] as $lineId => $values) {
                // Only scored is editable — criteria/target are immutable snapshots,
                // and merit is system-generated by KpiScoring::recompute below.
                $record->lines()->whereKey($lineId)->first()?->update([
                    'scored' => $values['scored'] ?? null,
                ]);
            }

            KpiScoring::recompute($record);
        });

        return redirect()->route('records.show', $record)
            ->with('status', 'Scorecard updated.');
    }

    public function destroy(KpiScorecard $record)
    {
        $record->delete();

        return redirect()->route('records.index')
            ->with('status', 'Scorecard deleted.');
    }
}
